"""add done_by_member_id to tasks

Revision ID: 2badfc088920
Revises: a404504053c9
Create Date: 2026-02-21 20:28:09.683232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2badfc088920"
down_revision: Union[str, None] = "a404504053c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("done_by_member_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_tasks_done_by_member_id"), "tasks", ["done_by_member_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "tasks",
        "team_members",
        ["done_by_member_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_done_by_member_id"), table_name="tasks")
    op.drop_column("tasks", "done_by_member_id")
    # ### end Alembic commands ###
