"""add active_team_id to users

Revision ID: 6f745071ac47
Revises: e8ff46433822
Create Date: 2026-02-14 13:11:12.810852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f745071ac47'
down_revision: Union[str, None] = 'e8ff46433822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_active_team_id'), 'users', ['active_team_id'], unique=False)
    op.create_foreign_key(None, 'users', 'teams', ['active_team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_active_team_id'), table_name='users')
    op.drop_column('users', 'active_team_id')
    # ### end Alembic commands ###
